shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground

allowBuilds:
  esbuild: false
  simple-git-hooks: true

overrides:
  fnv1a-64: 'workspace:*'

minimumReleaseAgeExclude:
  - fnv1a52@1.0.0
